Add files via upload
CDC-IITDH/cdc-placement-website-backend pull request #120
Opened 2022-05-28 17:34 UTC by kasv-p

place superuser.bat file in cdc_backend folder and setup.bat in cdc folder.
updated setup.sh
please check and review

2022-05-28 18:39 UTC, CDC-IITDH commented
Can you merge both `setup.bat` and `superuser.bat`. Like make it one file `setup.bat`

2022-05-30 08:21 UTC, gowtham3105 submitted a review, later dismissed
Merge both files

2022-05-30 10:43 UTC, karthikmurakonda requested changes

2022-05-30 10:43 UTC, karthikmurakonda commented on setup.bat
> +start superuser.bat &^
add this line:
`cd .. &^`
change the line:
`start .\superuser.bat &^`

2022-05-30 10:43 UTC, karthikmurakonda commented on superuser.bat
> +
add this line: `cd "CDC_Backend" &^`

2022-05-30 10:47 UTC, karthikmurakonda requested changes
.

2022-05-31 06:19 UTC, karthikmurakonda commented
closes #114

2022-06-05 08:58 UTC, gowtham3105 commented
Try to finish this by tomorrow

2022-06-06 13:57 UTC, karthikmurakonda approved these changes

2023-05-30 09:39 UTC, merged